### ISSUE TITLE
We are improving it!

### ISSUE THREAD

**Issue by highlightusingcss** [highlightusingcss/highlighter_css#1]
We made custom tags of HTML, How to write them?, To write it just add less than < and add the color name from the CSS kit and then add greater than to close the tag >

**Comment by highlightusingcss** [comment]
Get it!

**Comment by MasterOfSoftware-eng** [comment]
What did you mean by 'Get it!'?

**Comment by highlightusingcss** [comment]
I meant, Use it!

**Comment by MasterOfSoftware-eng** [comment]
Hey, announce everyone to use it!
